=== AdOnWeb/onphp-framework/meta/dtd/meta.dtd
<!-- $Id$ -->

<!ELEMENT metaconfiguration (plugin*, include*, classes*, sources*)>

<!ELEMENT classes (class*)>

<!ELEMENT class (implement*, properties*, pattern)>
<!ATTLIST class
		name		ID #REQUIRED
		type		(final|abstract) #IMPLIED
		extends		CDATA #IMPLIED
		source		CDATA #IMPLIED
		table		CDATA #IMPLIED
>

<!ELEMENT implement EMPTY>
<!ATTLIST implement
		interface	CDATA #REQUIRED
>

<!ELEMENT properties (identifier?, property*)>

<!ELEMENT identifier EMPTY>
<!ATTLIST identifier
		name	CDATA #IMPLIED
		type	CDATA #IMPLIED
		size	CDATA #IMPLIED
		column	CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
		name		CDATA #REQUIRED
		type		CDATA #REQUIRED
		size		CDATA #IMPLIED
		column		CDATA #IMPLIED
		default		CDATA #IMPLIED
		required	(true|false) "false"
		relation	(OneToOne|OneToMany|ManyToMany) #IMPLIED
		fetch		(lazy|cascade) #IMPLIED
		reference	(true|false) #IMPLIED
		helperTable CDATA #IMPLIED
>

<!ELEMENT pattern EMPTY>
<!ATTLIST pattern
		name		(
			DictionaryClass
			|AbstractClass
			|AbstractValueObject
			|StraightMapping
			|EnumerationClass
			|EnumClass
			|RegistryClass
			|SpookedClass
			|SpookedEnumeration
			|SpookedEnum
			|SpookedRegistry
			|ValueObject
			|InternalClass
			|NosqlClass
			|ObjectWithEmptyDAOClass
		) #REQUIRED
		fetch		(lazy|cascade) #IMPLIED
>

<!ELEMENT sources (source+)>

<!ELEMENT source EMPTY>
<!ATTLIST source
		name	CDATA #REQUIRED
		default	(true|false) "false"
>

<!-- file path is relative to current meta's directory -->
<!ELEMENT include EMPTY>
<!ATTLIST include
		file		CDATA #REQUIRED
		generate	(true|false) "true"
>

<!ELEMENT plugin EMPTY>
<!ATTLIST plugin
		name	CDATA #REQUIRED
		class	CDATA #REQUIRED
>

=== AdOnWeb/onphp-framework/meta/internal.xml
<?xml version="1.0"?>
<!DOCTYPE metaconfiguration SYSTEM "meta.dtd">

<!-- $Id$ -->

<metaconfiguration><classes>

	<class name="Range">
		<properties>
			<property name="min" type="Integer" required="false" />
			<property name="max" type="Integer" required="false" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="DateRange">
		<properties>
			<property name="start" type="Date" required="false" />
			<property name="end" type="Date" required="false" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>
	
	<class name="DateRange">
		<properties>
			<property name="start" type="Timestamp" required="false" />
			<property name="end" type="Timestamp" required="false" />
		</properties>
		
		<pattern name="InternalClass" />
	</class>

</classes></metaconfiguration>
